[functions]
crear-cliente.verify_jwt = true
proveedores.verify_jwt = true
productos.verify_jwt = true
proveedor-producto.verify_jwt = true
boticas.verify_jwt = true
usuarios.verify_jwt = true
auditoria.verify_jwt = true
ordenes-compra.verify_jwt = true
inventario-movimientos.verify_jwt = true
