import { Clock, Truck, CheckCircle, XCircle, AlertTriangle, RotateCcw, Undo2 } from 'lucide-react'

export const ESTADOS_TRANSFERENCIA = {
  CREADA: 'creada',
  APROBADA: 'aprobada',
  EN_TRANSITO: 'en_transito',
  RECIBIDA: 'recibida',
  CANCELADA: 'cancelada',
  RECHAZADA: 'rechazada',
  PENDIENTE_DEVOLUCION: 'pendiente_devolucion',
  DEVUELTA_A_ORIGEN: 'devuelta_a_origen',
}

export const ETIQUETAS_TRANSFERENCIA = {
  [ESTADOS_TRANSFERENCIA.CREADA]: 'Creada',
  [ESTADOS_TRANSFERENCIA.APROBADA]: 'Aprobada',
  [ESTADOS_TRANSFERENCIA.EN_TRANSITO]: 'En Tránsito',
  [ESTADOS_TRANSFERENCIA.RECIBIDA]: 'Recibida',
  [ESTADOS_TRANSFERENCIA.CANCELADA]: 'Cancelada',
  [ESTADOS_TRANSFERENCIA.RECHAZADA]: 'Rechazada',
  [ESTADOS_TRANSFERENCIA.PENDIENTE_DEVOLUCION]: 'Pendiente Devolución',
  [ESTADOS_TRANSFERENCIA.DEVUELTA_A_ORIGEN]: 'Devuelta a Origen',
}

export const COLORES_TRANSFERENCIA = {
  [ESTADOS_TRANSFERENCIA.CREADA]: 'amarillo',
  [ESTADOS_TRANSFERENCIA.APROBADA]: 'azul',
  [ESTADOS_TRANSFERENCIA.EN_TRANSITO]: 'azul',
  [ESTADOS_TRANSFERENCIA.RECIBIDA]: 'verde',
  [ESTADOS_TRANSFERENCIA.CANCELADA]: 'rojo',
  [ESTADOS_TRANSFERENCIA.RECHAZADA]: 'naranja',
  [ESTADOS_TRANSFERENCIA.PENDIENTE_DEVOLUCION]: 'morado',
  [ESTADOS_TRANSFERENCIA.DEVUELTA_A_ORIGEN]: 'azul',
}

export const ICONOS_ESTADO_TRANSFERENCIA = {
  [ESTADOS_TRANSFERENCIA.CREADA]: Clock,
  [ESTADOS_TRANSFERENCIA.APROBADA]: CheckCircle,
  [ESTADOS_TRANSFERENCIA.EN_TRANSITO]: Truck,
  [ESTADOS_TRANSFERENCIA.RECIBIDA]: CheckCircle,
  [ESTADOS_TRANSFERENCIA.CANCELADA]: XCircle,
  [ESTADOS_TRANSFERENCIA.RECHAZADA]: AlertTriangle,
  [ESTADOS_TRANSFERENCIA.PENDIENTE_DEVOLUCION]: RotateCcw,
  [ESTADOS_TRANSFERENCIA.DEVUELTA_A_ORIGEN]: Undo2,
}

export const OPCIONES_ESTADO_TRANSFERENCIA = Object.entries(ETIQUETAS_TRANSFERENCIA).map(([valor, etiqueta]) => ({
  valor,
  etiqueta,
}))

export const TRANSICIONES_ESTADOS = {
  [ESTADOS_TRANSFERENCIA.CREADA]: [ESTADOS_TRANSFERENCIA.APROBADA, ESTADOS_TRANSFERENCIA.CANCELADA],
  [ESTADOS_TRANSFERENCIA.APROBADA]: [ESTADOS_TRANSFERENCIA.EN_TRANSITO, ESTADOS_TRANSFERENCIA.CANCELADA],
  [ESTADOS_TRANSFERENCIA.EN_TRANSITO]: [ESTADOS_TRANSFERENCIA.RECIBIDA, ESTADOS_TRANSFERENCIA.PENDIENTE_DEVOLUCION],
  [ESTADOS_TRANSFERENCIA.RECIBIDA]: [],
  [ESTADOS_TRANSFERENCIA.CANCELADA]: [],
  [ESTADOS_TRANSFERENCIA.RECHAZADA]: [],
  [ESTADOS_TRANSFERENCIA.PENDIENTE_DEVOLUCION]: [ESTADOS_TRANSFERENCIA.DEVUELTA_A_ORIGEN],
  [ESTADOS_TRANSFERENCIA.DEVUELTA_A_ORIGEN]: [],
}
