export const ESTADOS_TRANSFERENCIA = {
  CREADA: 'creada',
  EN_TRANSITO: 'en_transito',
  RECIBIDA: 'recibida',
  CANCELADA: 'cancelada',
  RECHAZADA: 'rechazada',
}

export const ETIQUETAS_TRANSFERENCIA = {
  [ESTADOS_TRANSFERENCIA.CREADA]: 'Creada',
  [ESTADOS_TRANSFERENCIA.EN_TRANSITO]: 'En Tránsito',
  [ESTADOS_TRANSFERENCIA.RECIBIDA]: 'Recibida',
  [ESTADOS_TRANSFERENCIA.CANCELADA]: 'Cancelada',
  [ESTADOS_TRANSFERENCIA.RECHAZADA]: 'Rechazada',
}

export const COLORES_TRANSFERENCIA = {
  [ESTADOS_TRANSFERENCIA.CREADA]: 'amarillo',
  [ESTADOS_TRANSFERENCIA.EN_TRANSITO]: 'azul',
  [ESTADOS_TRANSFERENCIA.RECIBIDA]: 'verde',
  [ESTADOS_TRANSFERENCIA.CANCELADA]: 'rojo',
  [ESTADOS_TRANSFERENCIA.RECHAZADA]: 'naranja',
}

export const OPCIONES_ESTADO_TRANSFERENCIA = Object.entries(ETIQUETAS_TRANSFERENCIA).map(([valor, etiqueta]) => ({
  valor,
  etiqueta,
}))

export const TRANSICIONES_ESTADOS = {
  [ESTADOS_TRANSFERENCIA.CREADA]: [ESTADOS_TRANSFERENCIA.EN_TRANSITO, ESTADOS_TRANSFERENCIA.CANCELADA],
  [ESTADOS_TRANSFERENCIA.EN_TRANSITO]: [ESTADOS_TRANSFERENCIA.RECIBIDA, ESTADOS_TRANSFERENCIA.RECHAZADA],
  [ESTADOS_TRANSFERENCIA.RECIBIDA]: [],
  [ESTADOS_TRANSFERENCIA.CANCELADA]: [],
  [ESTADOS_TRANSFERENCIA.RECHAZADA]: [],
}
