export const registrosAuditoria = [
  {
    id: 'aud-001',
    usuario: 'Carlos Mendoza',
    usuarioId: 'usr-001',
    accion: 'Inicio de sesión',
    entidad: null,
    entidadId: null,
    detalle: 'Inicio de sesión desde IP 190.42.100.50',
    nivel: 'info',
    createdAt: '2026-05-22T08:00:00',
  },
  {
    id: 'aud-002',
    usuario: 'Carlos Mendoza',
    usuarioId: 'usr-001',
    accion: 'Actualización',
    entidad: 'Producto',
    entidadId: 'prod-003',
    detalle: 'Se actualizó el precio de venta de S/ 12.50 a S/ 14.00',
    nivel: 'info',
    createdAt: '2026-05-22T07:45:00',
  },
  {
    id: 'aud-003',
    usuario: 'Ana Torres',
    usuarioId: 'usr-002',
    accion: 'Creación',
    entidad: 'Transferencia',
    entidadId: 'trans-008',
    detalle: 'Se creó transferencia de Droguería Central a Botica Miraflores',
    nivel: 'info',
    createdAt: '2026-05-21T18:30:00',
  },
  {
    id: 'aud-004',
    usuario: 'Luis García',
    usuarioId: 'usr-003',
    accion: 'Rechazo',
    entidad: 'Transferencia',
    entidadId: 'trans-007',
    detalle: 'Se rechazó recepción de transferencia por productos dañados',
    nivel: 'advertencia',
    createdAt: '2026-05-21T16:00:00',
  },
  {
    id: 'aud-005',
    usuario: 'Carlos Mendoza',
    usuarioId: 'usr-001',
    accion: 'Desactivación',
    entidad: 'Usuario',
    entidadId: 'usr-006',
    detalle: 'Se desactivó al usuario Rosa Fernández',
    nivel: 'info',
    createdAt: '2026-05-21T15:30:00',
  },
  {
    id: 'aud-006',
    usuario: 'José Ramírez',
    usuarioId: 'usr-005',
    accion: 'Inicio de sesión',
    entidad: null,
    entidadId: null,
    detalle: 'Inicio de sesión fallido — contraseña incorrecta',
    nivel: 'error',
    createdAt: '2026-05-21T14:20:00',
  },
  {
    id: 'aud-007',
    usuario: 'Ana Torres',
    usuarioId: 'usr-002',
    accion: 'Actualización',
    entidad: 'Stock',
    entidadId: 'stk-045',
    detalle: 'Ajuste de inventario: -10 unidades por merma',
    nivel: 'advertencia',
    createdAt: '2026-05-21T11:15:00',
  },
  {
    id: 'aud-008',
    usuario: 'Pedro Castillo',
    usuarioId: 'usr-007',
    accion: 'Configuración',
    entidad: 'Sistema',
    entidadId: null,
    detalle: 'Se modificó el tiempo de sesión de 60 a 120 minutos',
    nivel: 'info',
    createdAt: '2026-05-21T10:00:00',
  },
  {
    id: 'aud-009',
    usuario: 'Carlos Mendoza',
    usuarioId: 'usr-001',
    accion: 'Creación',
    entidad: 'Usuario',
    entidadId: 'usr-008',
    detalle: 'Se creó el usuario Lucía Mendoza con rol Operador Logístico Central',
    nivel: 'info',
    createdAt: '2026-05-20T16:00:00',
  },
  {
    id: 'aud-010',
    usuario: 'Sistema',
    usuarioId: null,
    accion: 'Ejecución',
    entidad: 'Modelo ML',
    entidadId: null,
    detalle: 'Ejecución de predicción SARIMA+XGBoost completada. MAPE: 4.23%',
    nivel: 'info',
    createdAt: '2026-05-20T06:00:00',
  },
  {
    id: 'aud-011',
    usuario: 'María Torres',
    usuarioId: 'usr-004',
    accion: 'Inicio de sesión',
    entidad: null,
    entidadId: null,
    detalle: 'Inicio de sesión desde Botica Miraflores',
    nivel: 'info',
    createdAt: '2026-05-19T09:00:00',
  },
  {
    id: 'aud-012',
    usuario: 'Lucía Mendoza',
    usuarioId: 'usr-008',
    accion: 'Actualización',
    entidad: 'Proveedor',
    entidadId: 'prov-002',
    detalle: 'Se actualizó el lead time de 7 a 5 días',
    nivel: 'info',
    createdAt: '2026-05-19T08:30:00',
  },
  {
    id: 'aud-013',
    usuario: 'Sistema',
    usuarioId: null,
    accion: 'Alerta',
    entidad: 'Stock',
    entidadId: 'stk-012',
    detalle: 'Alerta de stock crítico: Paracetamol 500mg por debajo del mínimo',
    nivel: 'error',
    createdAt: '2026-05-19T07:00:00',
  },
  {
    id: 'aud-014',
    usuario: 'Carlos Mendoza',
    usuarioId: 'usr-001',
    accion: 'Exportación',
    entidad: 'Reporte',
    entidadId: null,
    detalle: 'Se exportó reporte de Kardex en formato PDF',
    nivel: 'info',
    createdAt: '2026-05-18T15:45:00',
  },
  {
    id: 'aud-015',
    usuario: 'José Ramírez',
    usuarioId: 'usr-005',
    accion: 'Creación',
    entidad: 'Movimiento',
    entidadId: 'mov-023',
    detalle: 'Se registró ingreso de 500 unidades de Amoxicilina 500mg',
    nivel: 'info',
    createdAt: '2026-05-18T14:00:00',
  },
]

export const TIPOS_NIVEL_AUDITORIA = ['info', 'advertencia', 'error']

export const ETIQUETAS_NIVEL_AUDITORIA = {
  info: 'Info',
  advertencia: 'Advertencia',
  error: 'Error',
}

export const COLORES_NIVEL_AUDITORIA = {
  info: 'azul',
  advertencia: 'amarillo',
  error: 'rojo',
}

export const ACCIONES_AUDITORIA = [
  'Inicio de sesión',
  'Creación',
  'Actualización',
  'Desactivación',
  'Configuración',
  'Exportación',
  'Rechazo',
  'Ejecución',
  'Alerta',
]

export const OPCIONES_ACCION_AUDITORIA = ACCIONES_AUDITORIA.map(a => ({
  valor: a,
  etiqueta: a,
}))
