export const paises = [
  { codigo: 'PE', nombre: 'Perú' },
  { codigo: 'US', nombre: 'Estados Unidos' },
  { codigo: 'DE', nombre: 'Alemania' },
  { codigo: 'ES', nombre: 'España' },
  { codigo: 'MX', nombre: 'México' },
  { codigo: 'CO', nombre: 'Colombia' },
  { codigo: 'CL', nombre: 'Chile' },
  { codigo: 'AR', nombre: 'Argentina' },
  { codigo: 'BR', nombre: 'Brasil' },
  { codigo: 'JP', nombre: 'Japón' },
  { codigo: 'CN', nombre: 'China' },
  { codigo: 'IN', nombre: 'India' },
  { codigo: 'FR', nombre: 'Francia' },
  { codigo: 'IT', nombre: 'Italia' },
  { codigo: 'GB', nombre: 'Reino Unido' },
  { codigo: 'CA', nombre: 'Canadá' },
  { codigo: 'AU', nombre: 'Australia' },
  { codigo: 'KR', nombre: 'Corea del Sur' },
  { codigo: 'CH', nombre: 'Suiza' },
  { codigo: 'NL', nombre: 'Países Bajos' },
]
