/**
 * Datos de prueba: Catálogo de productos farmacéuticos peruanos.
 * Alineado con Arquitectura Lógica v4 — tabla productos.
 */
export const productos = [
  {
    id: 'prod-001',
    codigoInterno: 'PARA-500MG',
    nombreComercial: 'Paracetamol 500mg',
    principioActivo: 'Paracetamol',
    formaFarmaceutica: 'tableta',
    concentracion: '500 mg',
    laboratorio: 'Medifarma',
    codigoBarras: '7750100012345',
    categoriaTerapeutica: 'Analgésico',
    clasificacion: 'OTC',
    requiereReceta: false,
    estado: 'activo',
    createdAt: '2024-01-15T08:00:00',
  },
  {
    id: 'prod-002',
    codigoInterno: 'AMOX-500MG',
    nombreComercial: 'Amoxicilina 500mg',
    principioActivo: 'Amoxicilina',
    formaFarmaceutica: 'cápsula',
    concentracion: '500 mg',
    laboratorio: 'Genfar',
    codigoBarras: '7750100012346',
    categoriaTerapeutica: 'Antibiótico',
    clasificacion: 'receta',
    requiereReceta: true,
    estado: 'activo',
    createdAt: '2024-01-20T09:00:00',
  },
  {
    id: 'prod-003',
    codigoInterno: 'IBUP-400MG',
    nombreComercial: 'Ibuprofeno 400mg',
    principioActivo: 'Ibuprofeno',
    formaFarmaceutica: 'tableta',
    concentracion: '400 mg',
    laboratorio: 'Farmindustria',
    codigoBarras: '7750100012347',
    categoriaTerapeutica: 'Antiinflamatorio',
    clasificacion: 'OTC',
    requiereReceta: false,
    estado: 'activo',
    createdAt: '2024-02-01T10:00:00',
  },
  {
    id: 'prod-004',
    codigoInterno: 'OMEPR-20MG',
    nombreComercial: 'Omeprazol 20mg',
    principioActivo: 'Omeprazol',
    formaFarmaceutica: 'cápsula',
    concentracion: '20 mg',
    laboratorio: 'IQFarma',
    codigoBarras: '7750100012348',
    categoriaTerapeutica: 'Antiácido',
    clasificacion: 'receta',
    requiereReceta: false,
    estado: 'activo',
    createdAt: '2024-02-10T08:00:00',
  },
  {
    id: 'prod-005',
    codigoInterno: 'LOSA-50MG',
    nombreComercial: 'Losartán 50mg',
    principioActivo: 'Losartán Potásico',
    formaFarmaceutica: 'tableta',
    concentracion: '50 mg',
    laboratorio: 'Medifarma',
    codigoBarras: '7750100012349',
    categoriaTerapeutica: 'Antihipertensivo',
    clasificacion: 'receta',
    requiereReceta: true,
    estado: 'activo',
    createdAt: '2024-02-15T09:00:00',
  },
  {
    id: 'prod-006',
    codigoInterno: 'METF-850MG',
    nombreComercial: 'Metformina 850mg',
    principioActivo: 'Metformina Clorhidrato',
    formaFarmaceutica: 'tableta',
    concentracion: '850 mg',
    laboratorio: 'Genfar',
    codigoBarras: '7750100012350',
    categoriaTerapeutica: 'Antidiabético',
    clasificacion: 'receta',
    requiereReceta: true,
    estado: 'activo',
    createdAt: '2024-03-01T08:00:00',
  },
  {
    id: 'prod-007',
    codigoInterno: 'CETI-10MG',
    nombreComercial: 'Cetirizina 10mg',
    principioActivo: 'Cetirizina Diclorhidrato',
    formaFarmaceutica: 'tableta',
    concentracion: '10 mg',
    laboratorio: 'Farmindustria',
    codigoBarras: '7750100012351',
    categoriaTerapeutica: 'Antihistamínico',
    clasificacion: 'OTC',
    requiereReceta: false,
    estado: 'activo',
    createdAt: '2024-03-10T10:00:00',
  },
  {
    id: 'prod-008',
    codigoInterno: 'DICL-GEL1',
    nombreComercial: 'Diclofenaco Gel 1%',
    principioActivo: 'Diclofenaco Dietilamonio',
    formaFarmaceutica: 'crema',
    concentracion: '1%',
    laboratorio: 'IQFarma',
    codigoBarras: '7750100012352',
    categoriaTerapeutica: 'Antiinflamatorio tópico',
    clasificacion: 'OTC',
    requiereReceta: false,
    estado: 'activo',
    createdAt: '2024-03-15T08:00:00',
  },
  {
    id: 'prod-009',
    codigoInterno: 'AZIT-500MG',
    nombreComercial: 'Azitromicina 500mg',
    principioActivo: 'Azitromicina',
    formaFarmaceutica: 'tableta',
    concentracion: '500 mg',
    laboratorio: 'AC Farma',
    codigoBarras: '7750100012353',
    categoriaTerapeutica: 'Antibiótico',
    clasificacion: 'receta',
    requiereReceta: true,
    estado: 'activo',
    createdAt: '2024-04-01T09:00:00',
  },
  {
    id: 'prod-010',
    codigoInterno: 'AMB-JARABE',
    nombreComercial: 'Ambroxol Jarabe',
    principioActivo: 'Ambroxol Clorhidrato',
    formaFarmaceutica: 'jarabe',
    concentracion: '15 mg/5 mL',
    laboratorio: 'Medifarma',
    codigoBarras: '7750100012354',
    categoriaTerapeutica: 'Mucolítico',
    clasificacion: 'OTC',
    requiereReceta: false,
    estado: 'activo',
    createdAt: '2024-04-10T08:00:00',
  },
  {
    id: 'prod-011',
    codigoInterno: 'CLON-0.5MG',
    nombreComercial: 'Clonazepam 0.5mg',
    principioActivo: 'Clonazepam',
    formaFarmaceutica: 'tableta',
    concentracion: '0.5 mg',
    laboratorio: 'AC Farma',
    codigoBarras: '7750100012355',
    categoriaTerapeutica: 'Ansiolítico',
    clasificacion: 'receta',
    requiereReceta: true,
    estado: 'inactivo',
    createdAt: '2024-05-01T10:00:00',
  },
  {
    id: 'prod-012',
    codigoInterno: 'RANI-150MG',
    nombreComercial: 'Ranitidina 150mg',
    principioActivo: 'Ranitidina',
    formaFarmaceutica: 'tableta',
    concentracion: '150 mg',
    laboratorio: 'Genfar',
    codigoBarras: '7750100012356',
    categoriaTerapeutica: 'Antiácido',
    clasificacion: 'receta',
    requiereReceta: false,
    estado: 'descontinuado',
    createdAt: '2024-01-10T08:00:00',
  },
]