export const productos = [
  {
    id: 'prod-001',
    codigoInterno: 'PRD-000001',
    nombreComercial: 'Paracetamol 500mg',
    formaFarmaceuticaId: 'ff-001',
    presentacion: 'Caja x 20 Tabletas',
    clasificacion: 'OTC',
    estado: 'activo',
    createdAt: '2024-01-15T08:00:00',
    modifiedAt: null,
    modifiedBy: null,
  },
  {
    id: 'prod-002',
    codigoInterno: 'PRD-000002',
    nombreComercial: 'Amoxicilina 500mg',
    formaFarmaceuticaId: 'ff-002',
    presentacion: 'Caja x 10 Tabletas',
    clasificacion: 'receta',
    estado: 'activo',
    createdAt: '2024-01-20T09:00:00',
    modifiedAt: null,
    modifiedBy: null,
  },
  {
    id: 'prod-003',
    codigoInterno: 'PRD-000003',
    nombreComercial: 'Ibuprofeno 400mg',
    formaFarmaceuticaId: 'ff-001',
    presentacion: 'Caja x 20 Tabletas',
    clasificacion: 'OTC',
    estado: 'activo',
    createdAt: '2024-02-01T10:00:00',
    modifiedAt: null,
    modifiedBy: null,
  },
  {
    id: 'prod-004',
    codigoInterno: 'PRD-000004',
    nombreComercial: 'Omeprazol 20mg',
    formaFarmaceuticaId: 'ff-002',
    presentacion: 'Caja x 20 Tabletas',
    clasificacion: 'receta',
    estado: 'activo',
    createdAt: '2024-02-10T08:00:00',
    modifiedAt: null,
    modifiedBy: null,
  },
  {
    id: 'prod-005',
    codigoInterno: 'PRD-000005',
    nombreComercial: 'Losartán 50mg',
    formaFarmaceuticaId: 'ff-001',
    presentacion: 'Caja x 20 Tabletas',
    clasificacion: 'receta',
    estado: 'activo',
    createdAt: '2024-02-15T09:00:00',
    modifiedAt: null,
    modifiedBy: null,
  },
  {
    id: 'prod-006',
    codigoInterno: 'PRD-000006',
    nombreComercial: 'Metformina 850mg',
    formaFarmaceuticaId: 'ff-001',
    presentacion: 'Caja x 30 Tabletas',
    clasificacion: 'receta',
    estado: 'activo',
    createdAt: '2024-03-01T08:00:00',
    modifiedAt: null,
    modifiedBy: null,
  },
  {
    id: 'prod-007',
    codigoInterno: 'PRD-000007',
    nombreComercial: 'Cetirizina 10mg',
    formaFarmaceuticaId: 'ff-001',
    presentacion: 'Caja x 20 Tabletas',
    clasificacion: 'OTC',
    estado: 'activo',
    createdAt: '2024-03-10T10:00:00',
    modifiedAt: null,
    modifiedBy: null,
  },
  {
    id: 'prod-008',
    codigoInterno: 'PRD-000008',
    nombreComercial: 'Diclofenaco Gel 1%',
    formaFarmaceuticaId: 'ff-014',
    presentacion: 'Tubo x 30 g',
    clasificacion: 'OTC',
    estado: 'activo',
    createdAt: '2024-03-15T08:00:00',
    modifiedAt: null,
    modifiedBy: null,
  },
  {
    id: 'prod-009',
    codigoInterno: 'PRD-000009',
    nombreComercial: 'Azitromicina 500mg',
    formaFarmaceuticaId: 'ff-001',
    presentacion: 'Caja x 10 Tabletas',
    clasificacion: 'receta',
    estado: 'activo',
    createdAt: '2024-04-01T09:00:00',
    modifiedAt: null,
    modifiedBy: null,
  },
  {
    id: 'prod-010',
    codigoInterno: 'PRD-000010',
    nombreComercial: 'Ambroxol Jarabe',
    formaFarmaceuticaId: 'ff-003',
    presentacion: 'Frasco x 250 mL',
    clasificacion: 'OTC',
    estado: 'activo',
    createdAt: '2024-04-10T08:00:00',
    modifiedAt: null,
    modifiedBy: null,
  },
  {
    id: 'prod-011',
    codigoInterno: 'PRD-000011',
    nombreComercial: 'Clonazepam 0.5mg',
    formaFarmaceuticaId: 'ff-001',
    presentacion: 'Ampolla x 1 Unidad',
    clasificacion: 'receta',
    estado: 'inactivo',
    createdAt: '2024-05-01T10:00:00',
    modifiedAt: null,
    modifiedBy: null,
  },
  {
    id: 'prod-012',
    codigoInterno: 'PRD-000012',
    nombreComercial: 'Ranitidina 150mg',
    formaFarmaceuticaId: 'ff-001',
    presentacion: 'Caja x 20 Tabletas',
    clasificacion: 'receta',
    estado: 'descontinuado',
    createdAt: '2024-01-10T08:00:00',
    modifiedAt: null,
    modifiedBy: null,
  },
]
