/**
 * Datos de prueba: Proveedores de medicamentos.
 * Alineado con Arquitectura Lógica v4 — tabla proveedores.
 * Soporta identificación polimórfica: RUC (Perú), NIT (Centroamérica), Tax ID, VAT, etc.
 */
export const proveedores = [
  {
    id: 'prov-001',
    razonSocial: 'Medifarma S.A.',
    tipoIdentificacion: 'ruc',
    numeroIdentificacion: '20123456789',
    paisOrigen: 'PE',
    contacto: 'María López',
    telefono: '01-4567890',
    correo: 'ventas@medifarma.com',
    direccion: 'Av. Argentina 2345, Cercado de Lima',
    ubigeo: '150101',
    distrito: 'Cercado de Lima',
    leadTimeDias: 5,
    condicionesPago: 'Crédito 30 días',
    activo: true,
    createdAt: '2024-01-15T08:00:00',
  },
  {
    id: 'prov-002',
    razonSocial: 'Genfar Perú S.A.C.',
    tipoIdentificacion: 'ruc',
    numeroIdentificacion: '20567890123',
    paisOrigen: 'PE',
    contacto: 'Roberto Díaz',
    telefono: '01-3456789',
    correo: 'comercial@genfar.pe',
    direccion: 'Calle Los Libertadores 456, San Isidrio',
    ubigeo: '150104',
    distrito: 'San Isidrio',
    leadTimeDias: 7,
    condicionesPago: 'Crédito 45 días',
    activo: true,
    createdAt: '2024-02-20T09:30:00',
  },
  {
    id: 'prov-003',
    razonSocial: 'IQFarma S.R.L.',
    tipoIdentificacion: 'ruc',
    numeroIdentificacion: '10456789012',
    paisOrigen: 'PE',
    contacto: 'Carlos Pérez',
    telefono: '01-2345678',
    correo: 'info@iqfarma.com',
    direccion: 'Av. Túpac Amaru 1234, Ate',
    ubigeo: '150108',
    distrito: 'Ate',
    leadTimeDias: 3,
    condicionesPago: 'Contado',
    activo: true,
    createdAt: '2024-03-10T10:00:00',
  },
  {
    id: 'prov-004',
    razonSocial: 'Farmindustria S.A.',
    tipoIdentificacion: 'ruc',
    numeroIdentificacion: '20198765432',
    paisOrigen: 'PE',
    contacto: 'Laura Mendoza',
    telefono: '01-5678901',
    correo: 'ventas@farmindustria.com',
    direccion: 'Av. Industrial 789, Villa El Salvador',
    ubigeo: '150109',
    distrito: 'Villa El Salvador',
    leadTimeDias: 10,
    condicionesPago: 'Crédito 60 días',
    activo: true,
    createdAt: '2024-04-05T14:00:00',
  },
  {
    id: 'prov-005',
    razonSocial: 'Inversiones FarmaSur E.I.R.L.',
    tipoIdentificacion: 'ruc',
    numeroIdentificacion: '20678901234',
    paisOrigen: 'PE',
    contacto: 'Pedro Sánchez',
    telefono: '01-6789012',
    correo: 'compras@farmaSur.pe',
    direccion: 'Av. Primavera 2345, Santiago de Surco',
    ubigeo: '150114',
    distrito: 'Santiago de Surco',
    leadTimeDias: 4,
    condicionesPago: 'Crédito 30 días',
    activo: false,
    createdAt: '2024-05-12T11:30:00',
  },
  {
    id: 'prov-006',
    razonSocial: 'Europharma GmbH',
    tipoIdentificacion: 'vat',
    numeroIdentificacion: 'DE123456789',
    paisOrigen: 'DE',
    contacto: 'Hans Mueller',
    telefono: '+49-30-12345678',
    correo: 'kontakt@europharma.de',
    direccion: 'Friedrichstrasse 123, Berlin',
    ubigeo: null,
    distrito: 'Berlin',
    leadTimeDias: 21,
    condicionesPago: 'Carta de crédito 60 días',
    activo: true,
    createdAt: '2024-06-01T09:00:00',
  },
  {
    id: 'prov-007',
    razonSocial: 'Asian Pharma Co Ltd',
    tipoIdentificacion: 'tax_id',
    numeroIdentificacion: 'JP1234567890123',
    paisOrigen: 'JP',
    contacto: 'Yuki Tanaka',
    telefono: '+81-3-1234-5678',
    correo: 'sales@asianpharma.jp',
    direccion: 'Shinjuku, Tokyo',
    ubigeo: null,
    distrito: 'Tokyo',
    leadTimeDias: 28,
    condicionesPago: 'Carta de crédito 90 días',
    activo: true,
    createdAt: '2024-07-01T10:00:00',
  },
]

export const TIPOS_IDENTIFICACION_PROVEEDOR = {
  RUC: 'ruc',
  NIT: 'nit',
  TAX_ID: 'tax_id',
  VAT: 'vat',
  OTRO: 'otro',
}