/**
 * Datos de referencia: Padrón de ubigeos INEI.
 * Alineado con Arquitectura Lógica v4 — tabla ubigeos.
 * Este dato es estático y no cambia.
 */
export const ubigeos = [
  { codigo: '150101', distrito: 'Cercado de Lima', provincia: 'Lima', departamento: 'Lima' },
  { codigo: '150102', distrito: 'Ate', provincia: 'Lima', departamento: 'Lima' },
  { codigo: '150103', provincia: 'Lima', departamento: 'Lima' },
  { codigo: '150104', distrito: 'Miraflores', provincia: 'Lima', departamento: 'Lima' },
  { codigo: '150105', distrito: 'San Juan de Lurigancho', provincia: 'Lima', departamento: 'Lima' },
  { codigo: '150106', distrito: 'Santiago de Surco', provincia: 'Lima', departamento: 'Lima' },
  { codigo: '150107', distrito: 'San Juan de Miraflores', provincia: 'Lima', departamento: 'Lima' },
  { codigo: '150108', distrito: 'Ate', provincia: 'Lima', departamento: 'Lima' },
  { codigo: '150109', distrito: 'Villa El Salvador', provincia: 'Lima', departamento: 'Lima' },
  { codigo: '150110', distrito: 'Chorrillos', provincia: 'Lima', departamento: 'Lima' },
  { codigo: '150111', provincia: 'Lima', departamento: 'Lima' },
  { codigo: '150112', provincia: 'Lima', departamento: 'Lima' },
  { codigo: '150113', distrito: 'Lurin', provincia: 'Lima', departamento: 'Lima' },
  { codigo: '150114', distrito: 'Santiago de Surco', provincia: 'Lima', departamento: 'Lima' },
  { codigo: '150115', distrito: 'Pueblo Libre', provincia: 'Lima', departamento: 'Lima' },
  { codigo: '150116', distrito: 'Magdalena del Mar', provincia: 'Lima', departamento: 'Lima' },
  { codigo: '150117', provincia: 'Lima', departamento: 'Lima' },
  { codigo: '150118', provincia: 'Lima', departamento: 'Lima' },
  { codigo: '150119', provincia: 'Lima', departamento: 'Lima' },
  { codigo: '150120', distrito: 'Breña', provincia: 'Lima', departamento: 'Lima' },
  { codigo: '150121', distrito: 'Los Olivos', provincia: 'Lima', departamento: 'Lima' },
  { codigo: '150122', distrito: 'San Miguel', provincia: 'Lima', departamento: 'Lima' },
  { codigo: '150123', distrito: 'Rímac', provincia: 'Lima', departamento: 'Lima' },
  { codigo: '150124', distrito: 'Barranco', provincia: 'Lima', departamento: 'Lima' },
  { codigo: '150125', distrito: 'Comas', provincia: 'Lima', departamento: 'Lima' },
  { codigo: '150126', provincia: 'Lima', departamento: 'Lima' },
  { codigo: '150127', provincia: 'Lima', departamento: 'Lima' },
  { codigo: '150128', provincia: 'Lima', departamento: 'Lima' },
  { codigo: '150129', provincia: 'Lima', departamento: 'Lima' },
  { codigo: '150130', provincia: 'Lima', departamento: 'Lima' },
  { codigo: '150131', provincia: 'Lima', departamento: 'Lima' },
  { codigo: '150132', provincia: 'Lima', departamento: 'Lima' },
  { codigo: '150133', provincia: 'Lima', departamento: 'Lima' },
  { codigo: '150134', provincia: 'Lima', departamento: 'Lima' },
  { codigo: '150135', provincia: 'Lima', departamento: 'Lima' },
  { codigo: '150136', provincia: 'Lima', departamento: 'Lima' },
  { codigo: '150137', provincia: 'Lima', departamento: 'Lima' },
  { codigo: '150138', provincia: 'Lima', departamento: 'Lima' },
  { codigo: '150139', provincia: 'Lima', departamento: 'Lima' },
  { codigo: '150140', provincia: 'Lima', departamento: 'Lima' },
  { codigo: '150141', provincia: 'Lima', departamento: 'Lima' },
  { codigo: '150142', provincia: 'Lima', departamento: 'Lima' },
  { codigo: '150143', distrito: 'San Borja', provincia: 'Lima', departamento: 'Lima' },
]