/**
 * Datos de prueba: Catálogo de productos farmacéuticos peruanos.
 * Incluye al menos 10 productos con datos realistas.
 */
export const productos = [
  {
    id: 'prod-001',
    nombreComercial: 'Paracetamol 500mg',
    principioActivo: 'Paracetamol',
    formaFarmaceutica: 'tableta',
    concentracion: '500 mg',
    laboratorio: 'Medifarma',
    codigoBarras: '7750100012345',
    clasificacion: 'otc',
    familiaATC: 'N',
    estado: 'activo',
    fechaCreacion: '2024-01-15',
  },
  {
    id: 'prod-002',
    nombreComercial: 'Amoxicilina 500mg',
    principioActivo: 'Amoxicilina',
    formaFarmaceutica: 'capsula',
    concentracion: '500 mg',
    laboratorio: 'Genfar',
    codigoBarras: '7750100012346',
    clasificacion: 'receta',
    familiaATC: 'J',
    estado: 'activo',
    fechaCreacion: '2024-01-20',
  },
  {
    id: 'prod-003',
    nombreComercial: 'Ibuprofeno 400mg',
    principioActivo: 'Ibuprofeno',
    formaFarmaceutica: 'tableta',
    concentracion: '400 mg',
    laboratorio: 'Farmindustria',
    codigoBarras: '7750100012347',
    clasificacion: 'otc',
    familiaATC: 'M',
    estado: 'activo',
    fechaCreacion: '2024-02-01',
  },
  {
    id: 'prod-004',
    nombreComercial: 'Omeprazol 20mg',
    principioActivo: 'Omeprazol',
    formaFarmaceutica: 'capsula',
    concentracion: '20 mg',
    laboratorio: 'IQFarma',
    codigoBarras: '7750100012348',
    clasificacion: 'generico',
    familiaATC: 'A',
    estado: 'activo',
    fechaCreacion: '2024-02-10',
  },
  {
    id: 'prod-005',
    nombreComercial: 'Losartán 50mg',
    principioActivo: 'Losartán Potásico',
    formaFarmaceutica: 'tableta',
    concentracion: '50 mg',
    laboratorio: 'Medifarma',
    codigoBarras: '7750100012349',
    clasificacion: 'receta',
    familiaATC: 'C',
    estado: 'activo',
    fechaCreacion: '2024-02-15',
  },
  {
    id: 'prod-006',
    nombreComercial: 'Metformina 850mg',
    principioActivo: 'Metformina Clorhidrato',
    formaFarmaceutica: 'tableta',
    concentracion: '850 mg',
    laboratorio: 'Genfar',
    codigoBarras: '7750100012350',
    clasificacion: 'receta',
    familiaATC: 'A',
    estado: 'activo',
    fechaCreacion: '2024-03-01',
  },
  {
    id: 'prod-007',
    nombreComercial: 'Cetirizina 10mg',
    principioActivo: 'Cetirizina Diclorhidrato',
    formaFarmaceutica: 'tableta',
    concentracion: '10 mg',
    laboratorio: 'Farmindustria',
    codigoBarras: '7750100012351',
    clasificacion: 'otc',
    familiaATC: 'R',
    estado: 'activo',
    fechaCreacion: '2024-03-10',
  },
  {
    id: 'prod-008',
    nombreComercial: 'Diclofenaco Gel 1%',
    principioActivo: 'Diclofenaco Dietilamonio',
    formaFarmaceutica: 'crema',
    concentracion: '1%',
    laboratorio: 'IQFarma',
    codigoBarras: '7750100012352',
    clasificacion: 'otc',
    familiaATC: 'D',
    estado: 'activo',
    fechaCreacion: '2024-03-15',
  },
  {
    id: 'prod-009',
    nombreComercial: 'Azitromicina 500mg',
    principioActivo: 'Azitromicina',
    formaFarmaceutica: 'tableta',
    concentracion: '500 mg',
    laboratorio: 'AC Farma',
    codigoBarras: '7750100012353',
    clasificacion: 'receta',
    familiaATC: 'J',
    estado: 'activo',
    fechaCreacion: '2024-04-01',
  },
  {
    id: 'prod-010',
    nombreComercial: 'Ambroxol Jarabe',
    principioActivo: 'Ambroxol Clorhidrato',
    formaFarmaceutica: 'jarabe',
    concentracion: '15 mg/5 mL',
    laboratorio: 'Medifarma',
    codigoBarras: '7750100012354',
    clasificacion: 'otc',
    familiaATC: 'R',
    estado: 'activo',
    fechaCreacion: '2024-04-10',
  },
  {
    id: 'prod-011',
    nombreComercial: 'Clonazepam 0.5mg',
    principioActivo: 'Clonazepam',
    formaFarmaceutica: 'tableta',
    concentracion: '0.5 mg',
    laboratorio: 'AC Farma',
    codigoBarras: '7750100012355',
    clasificacion: 'receta',
    familiaATC: 'N',
    estado: 'inactivo',
    fechaCreacion: '2024-05-01',
  },
  {
    id: 'prod-012',
    nombreComercial: 'Ranitidina 150mg',
    principioActivo: 'Ranitidina',
    formaFarmaceutica: 'tableta',
    concentracion: '150 mg',
    laboratorio: 'Genfar',
    codigoBarras: '7750100012356',
    clasificacion: 'generico',
    familiaATC: 'A',
    estado: 'descontinuado',
    fechaCreacion: '2024-01-10',
  },
]
